# Numpy

In [1]:
print 'hello'

hello


In [5]:
import numpy as np

# Change False to True for each block of code to see what it does

# Arithmetic operations between 2 NumPy arrays
if False:
    a = np.array([1, 2, 3, 4])
    b = np.array([1, 2, 1, 2])
    
    print a + b
    print a - b
    print a * b
    print a / b
    print a ** b
    
# Arithmetic operations between a NumPy array and a single number
if False:
    a = np.array([1, 2, 3, 4])
    b = 2
    
    print a + b
    print a - b
    print a * b
    print a / b
    print a ** b
    
# Logical operations with NumPy arrays
if True:
    a = np.array([True, True, False, False])
    b = np.array([True, False, True, False])

    
    print a & b
    print a | b
    print ~a
    
    print a & True
    print a & False
    
    print a | True
    print a | False
    
# Comparison operations between 2 NumPy Arrays
if False:
    a = np.array([1, 2, 3, 4, 5])
    b = np.array([5, 4, 3, 2, 1])
    
    print a > b
    print a >= b
    print a < b
    print a <= b
    print a == b
    print a != b
    
# Comparison operations between a NumPy array and a single number
if False:
    a = np.array([1, 2, 3, 4])
    b = 2
    
    print a > b
    print a >= b
    print a < b
    print a <= b
    print a == b
    print a != b
    

[1 0 3 0 1]
[5 6 3 6 5]
[-2 -3 -4 -5 -6]
[1 0 1 0 1]
[0 0 0 0 0]
[1 3 3 5 5]
[1 2 3 4 5]


In [6]:
countries = np.array([
    'Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
    'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
    'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
    'Belize', 'Benin', 'Bhutan', 'Bolivia',
    'Bosnia and Herzegovina'
])

# Employment data in 2007 for those 20 countries
employment = np.array([
    55.70000076,  51.40000153,  50.5       ,  75.69999695,
    58.40000153,  40.09999847,  61.5       ,  57.09999847,
    60.90000153,  66.59999847,  60.40000153,  68.09999847,
    66.90000153,  53.40000153,  48.59999847,  56.79999924,
    71.59999847,  58.40000153,  70.40000153,  41.20000076
])

In [9]:
std_data = employment.mean()
print std_data

58.68500003850001


In [12]:
def mean_time_for_paid_students(time_spent, days_to_cancel):
    '''
    Fill in this function to calculate the mean time spent in the classroom
    for students who stayed enrolled at least (greater than or equal to) 7 days.
    Unlike in Lesson 1, you can assume that days_to_cancel will contain only
    integers (there are no students who have not canceled yet).
    
    The arguments are NumPy arrays. time_spent contains the amount of time spent
    in the classroom for each student, and days_to_cancel contains the number
    of days until each student cancel. The data is given in the same order
    in both arrays.
    '''
    return None

# Time spent in the classroom in the first week for 20 students
time_spent = np.array([
       12.89697233,    0.        ,   64.55043217,    0.        ,
       24.2315615 ,   39.991625  ,    0.        ,    0.        ,
      147.20683783,    0.        ,    0.        ,    0.        ,
       45.18261617,  157.60454283,  133.2434615 ,   52.85000767,
        0.        ,   54.9204785 ,   26.78142417,    0.
])

# Days to cancel for 20 students
days_to_cancel = np.array([
      4,   5,  37,   3,  12,   4,  35,  38,   5,  37,   3,   3,  68,
     38,  98,   2, 249,   2, 127,  35
])
index_array = days_to_cancel > 7
print(index_array)

[False False  True False  True False  True  True False  True False False
  True  True  True False  True False  True  True]


In [13]:
mean_time_spent = time_spent[index_array]
print mean_time_spent

[ 64.55043217  24.2315615    0.           0.           0.
  45.18261617 157.60454283 133.2434615    0.          26.78142417
   0.        ]


In [14]:
x = [1,2,3,4]

In [15]:
y = x[:3]

In [16]:
y

[1, 2, 3]

In [17]:
y[0] = 6


In [18]:
y

[6, 2, 3]

In [19]:
x

[1, 2, 3, 4]

In [20]:
d = np.array([1,2,3,4,5])

In [21]:
d

array([1, 2, 3, 4, 5])

In [22]:
c = d[:3]

In [23]:
c

array([1, 2, 3])

In [24]:
c[0] = 6

In [25]:
c

array([6, 2, 3])

In [26]:
d

array([6, 2, 3, 4, 5])

In [27]:
import pandas as pd

countries = ['Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda',
             'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan',
             'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus',
             'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia']

life_expectancy_values = [74.7,  75. ,  83.4,  57.6,  74.6,  75.4,  72.3,  81.5,  80.2,
                          70.3,  72.1,  76.4,  68.1,  75.2,  69.8,  79.4,  70.8,  62.7,
                          67.3,  70.6]

gdp_values = [ 1681.61390973,   2155.48523109,  21495.80508273,    562.98768478,
              13495.1274663 ,   9388.68852258,   1424.19056199,  24765.54890176,
              27036.48733192,   1945.63754911,  21721.61840978,  13373.21993972,
                483.97086804,   9783.98417323,   2253.46411147,  25034.66692293,
               3680.91642923,    366.04496652,   1175.92638695,   1132.21387981]

# Life expectancy and gdp data in 2007 for 20 countries
life_expectancy = pd.Series(life_expectancy_values)
gdp = pd.Series(gdp_values)


In [36]:
print life_expectancy > life_expectancy.mean()
#print life_above_mean

0      True
1      True
2      True
3     False
4      True
5      True
6     False
7      True
8      True
9     False
10    False
11     True
12    False
13     True
14    False
15     True
16    False
17    False
18    False
19    False
dtype: bool


In [37]:
import pandas as pd

countries = [
    'Afghanistan', 'Albania', 'Algeria', 'Angola',
    'Argentina', 'Armenia', 'Australia', 'Austria',
    'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
    'Barbados', 'Belarus', 'Belgium', 'Belize',
    'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina',
]


employment_values = [
    55.70000076,  51.40000153,  50.5       ,  75.69999695,
    58.40000153,  40.09999847,  61.5       ,  57.09999847,
    60.90000153,  66.59999847,  60.40000153,  68.09999847,
    66.90000153,  53.40000153,  48.59999847,  56.79999924,
    71.59999847,  58.40000153,  70.40000153,  41.20000076,
]

# Employment data in 2007 for 20 countries
employment = pd.Series(employment_values, index=countries)

In [49]:
employment.idxmax()

'Angola'

In [48]:
employment.loc[employment.idxmax()]

75.69999695

In [47]:
for index, item in enumerate(employment):
    print 'position is {} employment {} index {} '.format(index,item)

index is 0 employment 55.70000076 
index is 1 employment 51.40000153 
index is 2 employment 50.5 
index is 3 employment 75.69999695 
index is 4 employment 58.40000153 
index is 5 employment 40.09999847 
index is 6 employment 61.5 
index is 7 employment 57.09999847 
index is 8 employment 60.90000153 
index is 9 employment 66.59999847 
index is 10 employment 60.40000153 
index is 11 employment 68.09999847 
index is 12 employment 66.90000153 
index is 13 employment 53.40000153 
index is 14 employment 48.59999847 
index is 15 employment 56.79999924 
index is 16 employment 71.59999847 
index is 17 employment 58.40000153 
index is 18 employment 70.40000153 
index is 19 employment 41.20000076 


## Numpy 2D Arrays

In [50]:
ridership = np.array([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
])

In [75]:
ridership[0,:].max()

5

3
3239.9
2342.6


In [ ]:
def mean_riders_for_max_station(ridership):
    '''
    Fill in this function to find the station with the maximum riders on the
    first day, then return the mean riders per day for that station. Also
    return the mean ridership overall for comparsion.
    
    Hint: NumPy's argmax() function might be useful:
    http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html
    '''
    overall_mean = None # Replace this with your code
    mean_for_max = None # Replace this with your code
    
    return (overall_mean, mean_for_max)

In [ ]:
def min_and_max_riders_per_day(ridership):
    '''
    Fill in this function. First, for each subway station, calculate the
    mean ridership per day. Then, out of all the subway stations, return the
    maximum and minimum of these values. That is, find the maximum
    mean-ridership-per-day and the minimum mean-ridership-per-day for any
    subway station.
    '''
    max_daily_ridership = ridership.max(axis=)     # Replace this with your code
    min_daily_ridership = None     # Replace this with your code
    
    return (max_daily_ridership, min_daily_ridership)

In [81]:
mean_per_station = ridership.mean(axis=0)

In [85]:
mean_per_station.argmin()

0

In [86]:
ridership.dtype

dtype('int64')